//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuPrimeiroProjetoWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_MEUPROJETOWEBEntities : DbContext
    {
        public BD_MEUPROJETOWEBEntities()
            : base("name=BD_MEUPROJETOWEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TabelaExemplo> TabelaExemplo { get; set; }
        public virtual DbSet<TabelaExemplo2> TabelaExemplo2 { get; set; }
    }
}
